In [1]:
import warnings; warnings.filterwarnings('ignore')

### Example 1

In [2]:
#load data
from ggplot import mtcars
x = mtcars[['mpg', 'drat', 'wt', 'qsec']].values

In [3]:
import oxyba as ox
r,p = ox.corr(x)

In [4]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)
print("sample correlation\n", r)
print("\np-values\n", p)
print("\nsubstantial corr?\n", p < 0.05)

sample correlation
 [[ 1.     0.681 -0.868  0.419]
 [ 0.681  1.    -0.712  0.091]
 [-0.868 -0.712  1.    -0.175]
 [ 0.419  0.091 -0.175  1.   ]]

p-values
 [[0.    0.    0.    0.017]
 [0.    0.    0.    0.62 ]
 [0.    0.    0.    0.339]
 [0.017 0.62  0.339 0.   ]]

substantial corr?
 [[ True  True  True  True]
 [ True  True  True False]
 [ True  True  True False]
 [ True False False  True]]
