In [1]:
import numpy as np
import oxyba as ox; 
from importlib import reload; reload(ox);

### Drop it - All entries are NaN/Inf
* remove data items (examples, records) that contain contain no usable variables
* not usuable values are `None`, `nan`, and `inf` (division by 0)

In [2]:
x = np.array([[1,2,3], [np.nan, np.inf, np.nan]])
print(x)

[[ 1.  2.  3.]
 [nan inf nan]]


In [3]:
y = ox.drop_empty_records(x)
print(y)

[[1. 2. 3.]]


### Keep it - Data points are just incomplete

In [4]:
x = np.array([[1,2,3], [np.nan, 1, np.nan]])
print(x)

[[ 1.  2.  3.]
 [nan  1. nan]]


In [5]:
y = ox.drop_empty_records(x)
print(y)

[[ 1.  2.  3.]
 [nan  1. nan]]
