In [1]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np
import oxyba as ox
from importlib import reload; reload(ox);

### Test Data
The python variable `x` contain two uncorrelated random numbers (columns).

In [2]:
x = [[0.751267059305653,0.959291425205444],
     [0.255095115459269,0.547215529963803],
     [0.505957051665142,0.138624442828679],
     [0.699076722656686,0.149294005559057],
     [0.890903252535799,0.257508254123736]];
x = np.array(x)
x

array([[0.75126706, 0.95929143],
       [0.25509512, 0.54721553],
       [0.50595705, 0.13862444],
       [0.69907672, 0.14929401],
       [0.89090325, 0.25750825]])

Given $\rho=0.5$ the bivariate correlated random numbers should be

```
    0.7513    1.2064
    0.2551    0.6015
    0.5060    0.3730
    0.6991    0.4788
    0.8909    0.6685
```

### Bivariate Correlation
Let $X_1$ and $X_2$ two uncorrelated normal distributed random numbers,
$rho$ the desired (Pearson) correlated coefficient, 
then 

$$
Y_1 = X_1 \\
Y_2 = \rho X_1 + \sqrt{1 - \rho^2} \, X_2
$$

are two $\phi$ correlated random numbers.



In [3]:
rho = .5
Y = ox.rand_bivar(x, rho)
Y

array([[0.75126706, 1.20640427],
       [0.25509512, 0.60145011],
       [0.50595705, 0.37303081],
       [0.69907672, 0.47883076],
       [0.89090325, 0.66846032]])

### Compare to rand_chol
The function `rand_chol` will create the same result
but requires to specify the full correlation matrix `rho`.

In [4]:
rho =  [[1,.5], [.5,1]]
Y = ox.rand_chol(x,rho)
Y

array([[0.75126706, 1.20640427],
       [0.25509512, 0.60145011],
       [0.50595705, 0.37303081],
       [0.69907672, 0.47883076],
       [0.89090325, 0.66846032]])