In [1]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np
import oxyba as ox
from importlib import reload; reload(ox);

### Lurie-Goldberg Algorithm
The Lurie-Goldberg Algorithm is based on the idea that 
$L\,L^T$ is always a semi-positive definite matrix 
with $L$ the lower triangular matrix of a Cholesky decomposition.

Let $R \in \mathbb{R}^{d\times d}$ a given ill-conditioned correlation matrix (e.g. subjective correlations from expert opinions), 
$L = (l_{ij})$ a lower triangular matrix,
and $C \in \mathbb{R}^{d\times d}$ the correlation matrix $C = L \, L^T$.

$$
\min_{l_{ij}} \frac{1}{2} \, || R - L \, L^T ||^2 
$$

The number of parameters is $(d^2+d)/2$

### Example 1
Load an ill-conditioned matrix

In [2]:
R = ox.illcond_corrmat(4, random_state=2)
print("Ill-conditioned Correlation Matrix")
print(R.round(3))

Ill-conditioned Correlation Matrix
[[ 1.    -0.948  0.099 -0.129]
 [-0.948  1.    -0.591  0.239]
 [ 0.099 -0.591  1.     0.058]
 [-0.129  0.239  0.058  1.   ]]


The k-Factor method for comparision

In [3]:
C,_,_,_,_ = ox.subjcorr_kfactor(R,4)
print("Fitted Correlation Matrix")
print(C.round(3))
print("Is Det(C)>=0 ? ", np.linalg.det(C))
print("\nDiff")
print(np.abs(R-C).round(4))

Fitted Correlation Matrix
[[ 1.    -0.885  0.337 -0.188]
 [-0.885  1.    -0.536  0.205]
 [ 0.337 -0.536  1.     0.668]
 [-0.188  0.205  0.668  1.   ]]
Is Det(C)>=0 ?  1.6620592691407305e-08

Diff
[[0.     0.063  0.2381 0.0587]
 [0.063  0.     0.0546 0.0331]
 [0.2381 0.0546 0.     0.6096]
 [0.0587 0.0331 0.6096 0.    ]]


And the Lurie-Goldberg method

In [4]:
C, L, results = ox.subjcorr_luriegold(R)
print("Fitted Correlation Matrix")
print(C.round(3))
print("Is Det(C)>=0 ? ", np.linalg.det(C))
print("\nDiff")
print(np.abs(R-C).round(4))

Fitted Correlation Matrix
[[ 1.    -0.885  0.128 -0.138]
 [-0.885  1.    -0.555  0.227]
 [ 0.128 -0.555  1.     0.053]
 [-0.138  0.227  0.053  1.   ]]
Is Det(C)>=0 ?  1.095672105281764e-08

Diff
[[0.     0.0633 0.029  0.0089]
 [0.0633 0.     0.036  0.011 ]
 [0.029  0.036  0.     0.005 ]
 [0.0089 0.011  0.005  0.    ]]


### Example 2

In [5]:
R = ox.illcond_corrmat(8, random_state=23)
print("Ill-conditioned Correlation Matrix")
print(R.round(2))

Ill-conditioned Correlation Matrix
[[ 1.    0.89  0.53 -0.44 -0.56  0.37 -0.67 -0.22]
 [ 0.89  1.   -1.    0.77  0.77 -0.4   0.18  0.96]
 [ 0.53 -1.    1.   -0.42  0.64  0.25 -0.78 -1.  ]
 [-0.44  0.77 -0.42  1.    0.74 -0.14  0.66  0.44]
 [-0.56  0.77  0.64  0.74  1.   -0.07 -0.68  0.1 ]
 [ 0.37 -0.4   0.25 -0.14 -0.07  1.    0.01 -0.21]
 [-0.67  0.18 -0.78  0.66 -0.68  0.01  1.   -0.84]
 [-0.22  0.96 -1.    0.44  0.1  -0.21 -0.84  1.  ]]


In [6]:
C, L, results = ox.subjcorr_luriegold(R)
print("Fitted Correlation Matrix")
print(C.round(2))
print("Is Det(C)>=0 ? ", np.linalg.det(C))
print("\nDiff")
print(np.abs(R-C).round(2))

Fitted Correlation Matrix
[[ 1.    0.29  0.25 -0.4  -0.19  0.28 -0.44 -0.  ]
 [ 0.29  1.   -0.58  0.64  0.32 -0.27 -0.04  0.73]
 [ 0.25 -0.58  1.   -0.48  0.3   0.28 -0.51 -0.63]
 [-0.4   0.64 -0.48  1.    0.56 -0.17  0.42  0.35]
 [-0.19  0.32  0.3   0.56  1.   -0.12 -0.4   0.23]
 [ 0.28 -0.27  0.28 -0.17 -0.12  1.   -0.03 -0.27]
 [-0.44 -0.04 -0.51  0.42 -0.4  -0.03  1.   -0.31]
 [-0.    0.73 -0.63  0.35  0.23 -0.27 -0.31  1.  ]]
Is Det(C)>=0 ?  5.523811327071143e-25

Diff
[[0.   0.61 0.28 0.04 0.37 0.09 0.23 0.21]
 [0.61 0.   0.42 0.13 0.45 0.13 0.22 0.23]
 [0.28 0.42 0.   0.06 0.35 0.03 0.27 0.36]
 [0.04 0.13 0.06 0.   0.18 0.03 0.24 0.09]
 [0.37 0.45 0.35 0.18 0.   0.05 0.28 0.13]
 [0.09 0.13 0.03 0.03 0.05 0.   0.05 0.06]
 [0.23 0.22 0.27 0.24 0.28 0.05 0.   0.53]
 [0.21 0.23 0.36 0.09 0.13 0.06 0.53 0.  ]]


### Links
* Philip M. Lurie, Matthew S. Goldberg, 1998. An Approximate Method for Sampling Correlated Random Variables from Partially-Specified Distributions. Management Science 44, 203–218. [researchgate](https://www.researchgate.net/profile/Philip_Lurie/publication/227447095_An_Approximate_Method_for_Sampling_Correlated_Random_Variables_from_Partially-Specified_Distributions/links/562ec86f08aef25a2444538c.pdf), 
