In [1]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np
import oxyba as ox
from importlib import reload; reload(ox);

### The One-Parameter Correlation Matrix

Let $C \in \mathbb{R}^{d\times d}$ a correlation matrix
with 1s as diagonal elements 
and $c_{ij}=x \forall i\neq j$ (i.e. one common parameter $x$ for all other coefficients)

$$
C = \left(\begin{array}{ccc} 1 & x & x\\ x & 1 & x\\ x & x & 1  \end{array}\right) \quad x\in\mathbb{R}
$$

Let $R \in \mathbb{R}^{d\times d}$ an ill-conditioned correlation matrix (e.g. subjective correlations from expert opinions) then $x$ is the solution for the optimization problem

$$
\min_x || R - C(x) || 
$$

One analytic solution is 

$$
x = \frac{ \mathbf{1}^T \, R \, \mathbf{1} + {\rm tr}(R) }{d^2-d} 
	\qquad  {\rm with} \quad \frac{-1}{d-1} \leq x \leq 1
$$


### Example

First, create a random ill-conditioned correlation matrix for three variables.

In [2]:
d = 3
R = ox.illcond_corrmat(d, random_state=2)
R

array([[ 1.        , -0.94814754,  0.09932496],
       [-0.94814754,  1.        , -0.33933036],
       [ 0.09932496, -0.33933036,  1.        ]])

Second, try to compute a feasible solution for $x$

In [3]:
C = ox.subjcorr_onepara(R)
C

array([[1.        , 0.60394902, 0.60394902],
       [0.60394902, 1.        , 0.60394902],
       [0.60394902, 0.60394902, 1.        ]])

As a last check try to create the Cholesky matrix from $C$.
If it does not work, numpy would throw an exception.

In [4]:
np.linalg.cholesky(C)

array([[1.        , 0.        , 0.        ],
       [0.60394902, 0.79702295, 0.        ],
       [0.60394902, 0.30011006, 0.73836274]])

Looks Ok.

### Example - No Solution Possible

The next example will demonstrate what happens if the analytic solution cannot be found for a given ill-conditioned matrix $R$

In [5]:
d = 3
R = ox.illcond_corrmat(d, random_state=234)
R

array([[ 1.        , -0.49143585,  0.82480089],
       [-0.49143585,  1.        ,  0.39761483],
       [ 0.82480089,  0.39761483,  1.        ]])

The function `subjcorr_onepara` will return `None` and a error message.

In [6]:
C = ox.subjcorr_onepara(R)

No analytic solution found x=1.2436599540117548


In most cases the coefficients $c_{ij}$ are too big.